### ISSUE TITLE
hota build  aspect not regular

### ISSUE THREAD

**Issue by Dep2020** [aeon0/d4lf#106]
![not regular aspect](https://github.com/aeon0/d4lf/assets/151978537/25ece8e6-5d4d-41d0-8111-9449cd1679f5)

why doesn't it recognize an aspect of the hota build?

**Comment by aeon0** [comment]
Did you add this anywhere:
```yaml
Aspects:
  - aspect_of_ancestral_force
```

The default barb.yaml profile does not include any aspects right now. The defaults are more examples. In the end, you probably want to build your own filter profile tailored to your needs and your build.
