### ISSUE TITLE
Feature to create .json files based on online builds

### ISSUE THREAD

**Issue by marceloavf** [aeon0/d4lf#109]
Would be good to have something based on matching builds from websites, for example:

- Use a link of d4builds or mobalytics and automatically generate .json files for it
- Some UI to organize it, activate or disable builds to check for instead of messing up with json files

**Comment by deadcode0815** [comment]
I'm testing around https://github.com/danparizher/maxroll-d4-scraper which at least scrapes builds from maxroll. It creates .json files.

**Comment by NoNameTrademark** [comment]
Someone needs to create translation.json for d4lf. No one has said present yet.

**Comment by SaGer27** [comment]
> I'm testing around https://github.com/danparizher/maxroll-d4-scraper which at least scrapes builds from maxroll. It creates .json files.

that would be nice bro!!

**Comment by SL048** [comment]
Hi guys, 
you can look at https://github.com/SL048/D4lf-maxroll-config-generator

**Comment by cjshrader** [comment]
It's not JSON files, but I believe this is complete as the gui now lets you import from popular build sites.
