### ISSUE TITLE
Fails to properly recognize The Grandfather

### ISSUE THREAD

**Issue by andrewlin12** [aeon0/d4lf#118]
Console showed this warning when I (very luckily) had The Grandfather drop:

```
[3.3.1 2023-12-19 05:35:55,124] WARNING    item.read_descr.read_descr: Could not find affix: ignores loss
```

**Comment by aeon0** [comment]
Oh yeah. I filter out the word "durability" since I dont want to have it e.g. for "Durability: 100/100". Grandfathers affix is the only one that also includes it.

I will filter out "Durability:" which should fix this. Good catch.

I dont have too many Grandfathers to test on ^^

**Comment by andrewlin12** [comment]
Thanks for fixing this so quickly!
