### ISSUE TITLE
item.descr.read_descr.read_descr: Could not find aspect/unique: <function clean_str at 0x00000191187B6A20>

### ISSUE THREAD

**Issue by takenek** [aeon0/d4lf#143]
[3.4.2 2024-01-08 13:25:12,526] WARNING    item.descr.read_descr.read_descr: Could not find aspect/unique: <function clean_str at 0x00000191187B6A20>
![image](https://github.com/aeon0/d4lf/assets/4953735/d83515ad-d5db-4fa3-b67c-5e5940e8cbfb)
![image](https://github.com/aeon0/d4lf/assets/4953735/6d98f5f8-608c-45de-9d97-542ca7095a9c)

**Comment by aeon0** [comment]
should be ok with 4.0.1. I added it as a unittest just in case
