### ISSUE TITLE
unsupported resolution

### ISSUE THREAD

**Issue by zaibas** [aeon0/d4lf#152]
just found out about this, and sadly my resolution isnt supported, any chance you can add support for 3840x1600, is there anything you need from me to do so?

**Comment by aeon0** [comment]
I assume 3840x1660, right? I will check if nvida dsr allows me to use 1660p. If not I would need templates as found here: https://github.com/aeon0/d4lf/tree/main/assets/templates_2160p with your resolution

**Comment by zaibas** [comment]
cant believe i missed that typo, its 3840x1600, if you cant use dsr for it please tell me and ill work on the templates :)

**Comment by aeon0** [comment]
I can do 1620p. You sure its 3840x1600 and not 3840x1620?

**Comment by zaibas** [comment]
sadly yes, it is indeed 3840x1600.  seemingly all of the 38 in ultrawides use it.

**Comment by aeon0** [comment]
If you provide the templates for 1600p, I can add the support for it.

**Comment by zaibas** [comment]
ok, i can do that, are the non medium font size ones done with small or large font? i took screenshots of everything medium and small as needed, can do large for the unlabeled ones if thats what they were supposed to be though. are there any guidelines for the specifics of trimming each image?

**Comment by aeon0** [comment]
Non medium one are done with small font size. Thanks. Guidelines are to have it also close as possible to what the  1080p one are. But dont need to be pixel perfect.

One question regarding 3840x1600 res. Does it have black bars at the left and right? e.g. the ultra wide resolutions for 2160p and 1440p have that. I would need to know the width of the bars (in pixels). Or you just take a sample screenshot ingame and I measure myself.

**Comment by zaibas** [comment]
no black bars, i included a screenshot ingame as well just incase, everything is trimmed hopefully well enough, if there are any issues please tell me :) 
[3840x1600.zip](https://github.com/aeon0/d4lf/files/14043465/3840x1600.zip)

**Comment by zaibas** [comment]
awesome it looks to be working, at least from the bit i teted using the default filters both in vision and auto mode.  thank you very much :)
