### ISSUE TITLE
[SUGGESTION] Add support for new aspects introduced in S3

### ISSUE THREAD

**Issue by JoShMiQueL** [aeon0/d4lf#153]
They have added several new aspects such as the following:
![image](https://github.com/aeon0/d4lf/assets/26714939/3a3f0884-fa7c-4909-a977-1f91b54a460a)

**Comment by aeon0** [comment]
Yep, will update them asap 👍

**Comment by aeon0** [comment]
See: https://github.com/aeon0/d4lf/releases/tag/v4.1.0
