### ISSUE TITLE
Error on 2 items

### ISSUE THREAD

**Issue by DanzoDev** [aeon0/d4lf#167]
**failed_itempower_itemtype**
![failed_itempower_itemtype_20240203_173611](https://github.com/aeon0/d4lf/assets/43318567/000c9b0f-b7f5-4b56-9e3f-33823c3f60ec)

**failed_affixes**
![failed_affixes_20240203_165641](https://github.com/aeon0/d4lf/assets/43318567/c2ed0cbb-9dc8-420c-9730-29a543d447c4)

**Comment by aeon0** [comment]
The legendary one I could fix by changing the pre processing a bit. But its just one of the cases were the OCR didnt properly detect the text.

For the rare one I dont have an easy fix. In the end I would suggest to turn of the auto compare feature when using d4lf.

**Comment by aeon0** [comment]
The top one is fixed on 4.1.3
