### ISSUE TITLE
Missing aspects of vampire skills 

### ISSUE THREAD

**Issue by German2Orbit** [aeon0/d4lf#193]
I wanted to ask if the missing vampire skills aspects will be added to the loot filter, that would still be worthwhile, since the new season is not coming until May :)

Kind regards 

![Screenshot 2024-03-21 003623](https://github.com/aeon0/d4lf/assets/20713524/3ad9e3fb-afad-4019-809e-1387e1b6b77c)

**Comment by BimmerHex** [comment]
You can add it to the bottom of the Aspects.json file like the others.

```
"hectic": {
        "desc": "after casting basic skills, one of your active cooldowns is reduced by seconds.",
        "snoId": 1106428,
        "full": "After casting {c_number}[Affix.\"Static Value 0\"]{/c} {c_important}Basic{/c} Skills, one of your active Cooldowns is reduced by {c_random}[Affix_Flat_Value_1]{/c} seconds.",
        "num_idx": [
            1
        ]
    },
```

**Comment by aeon0** [comment]
Added in v4.1.6
