### ISSUE TITLE
Validation Errors from scraped profile

### ISSUE THREAD

**Issue by Massemassimo** [aeon0/d4lf#236]
I had the tool scrape: https://maxroll.gg/d4/planner/qqvi0wdb

I get the following errors:
[5.1.1 2024-05-22 19:06:06,891] ERROR      item.filter.load_files: Validation errors in C:\Users\CG\.d4lf\profiles\shadowendgame.yaml
[5.1.1 2024-05-22 19:06:07,073] ERROR      item.filter.load_files: 10 validation errors for ProfileModel
Affixes.0.NecromancerHelm.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Affixes.1.NecromancerChestArmor.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Affixes.2.NecromancerGloves.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Affixes.3.NecromancerPants.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Affixes.4.NecromancerBoots.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Affixes.5.NecromancerAmulet.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Affixes.6.NecromancerRing.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Affixes.7.NecromancerRing2.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Affixes.8.NecromancerScythe.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
Affixes.9.NecromancerFocus.affixPool.0.minGreaterAffixCount
  Value error, must be at least 1 [type=value_error, input_value=0, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
[5.1.1 2024-05-22 19:06:07,076] ERROR      item.filter.load_files: Errors occurred while loading profiles, please check the log for details

Changing every "minGreaterAffixCount" to 1 in the profile does solve the errors but that's hardly a solution. :)

**Comment by chrisoro** [comment]
Fixed here: https://github.com/aeon0/d4lf/pull/237
