### ISSUE TITLE
minCount of 0 not allowed on affixPool

### ISSUE THREAD

**Issue by tomas-davidovic** [aeon0/d4lf#240]
Would it be possible to allow `minCount` of 0 on the affixPool?
That way I can have the profile with "inactive" affixPools where I have things I want, but not right now.
(I know it is possible to comment out the pool, but I don't see a reason to not allow minCount of 0)

**Comment by chrisoro** [comment]
Already done https://github.com/aeon0/d4lf/pull/237. Will be available with the next release
