### ISSUE TITLE
PR 250 removed import doc

### ISSUE THREAD

**Issue by hhdx01** [aeon0/d4lf#256]
https://github.com/aeon0/d4lf/pull/250 removed import documentation from README.md, I was pretty confused about the feature mentioned in the issues but nowhere else.

**Comment by chrisoro** [comment]
Well all of the gui needs still to be documented in the readme. open point

**Comment by hhdx01** [comment]
Well it's not the GUI doc missing, but also the Import build docs that were added earlier and can work without GUI see https://github.com/aeon0/d4lf/pull/250/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L314

**Comment by chrisoro** [comment]
There are no other importers anymore, just the GUI. Hence, we removed that documentation

**Comment by hhdx01** [comment]
Fair enough
