### ISSUE TITLE
FileNotFoundError : Errno 2

### ISSUE THREAD

**Issue by nightsebibi** [aeon0/d4lf#33]
I have this error and there is no log file created

![Capture d’écran 2023-11-05 170604](https://github.com/aeon0/d4lf/assets/82817147/6f785140-3d9e-4ea7-81b6-44351b4b69d2)

**Comment by aeon0** [comment]
Yeah. I added a check to look in the localprefs game settings if the user has properly set the font size to small. But I did not realize that the location of this setting file can be different depending on the local setup. E.g. if you are using steam, this file is at a totaly different location. I will fix this in the upcoming release. Will keep the issue open for the time being.

**Comment by nightsebibi** [comment]
ok. I'm using Battlenet. I redirected Documents to another hard drive for easier backup.

**Comment by aeon0** [comment]
Yes, stuff like this I did not consider. sry about that.

**Comment by aeon0** [comment]
Should be resolved with https://github.com/aeon0/d4lf/releases/tag/v1.3.4
