### ISSUE TITLE
Constant Warnings in Logs: "Template not defined: item_mythic_top_left"

### ISSUE THREAD

**Issue by JoShMiQueL** [aeon0/d4lf#343]
### Description:
I am encountering constant warnings in the logs, which appear to be spamming the output. The warning message is as follows:
```css
[WARNING] | src.template_finder:119 | Template not defined: item_mythic_top_left
```
This issue makes it difficult to read through the logs and identify other important information.
### Steps to Reproduce:
1. Run the project as per the instructions.
2. Observe the logs for a period of time.
3. Note the repetitive warning messages.
### Expected Behavior:
The warning messages should not be spammed continuously. Either the missing template should be addressed, or the warning should be minimized to avoid log flooding.
### Screenshots:
![Captura de pantalla 2024-08-06 192911](https://github.com/user-attachments/assets/7f559fe2-3fb8-4210-afc1-233ffd841d0f)
### Environment:
- OS: Windows 11 Pro 10.0.22631 Build 22631
- Python Version: Python 3.11.9
- Project Version: [v5.7.0beta3](https://github.com/aeon0/d4lf/releases/tag/v5.7.0beta3)

**Comment by Lauriy** [comment]
![mythic_bullet_point](https://github.com/user-attachments/assets/9b3d5b9b-d7ab-4aaa-8b70-44de202bd1be)
![mythic_bullet_point_medium](https://github.com/user-attachments/assets/896f9b18-9e22-4382-916e-58a294916607)
![item_mythic_top_left](https://github.com/user-attachments/assets/50452c51-df4e-423a-9d90-d8ab77fd42b9)
I put these into my folder to quiet down the warning, but detection isn't working. I guess I'm bad at cropping.
