### ISSUE TITLE
VirusTotal reporting Malware?

### ISSUE THREAD

**Issue by x-ProgrammEd-x** [aeon0/d4lf#356]
Hi all,

is this thing safe? Running the *.exe through Virustotal results in 5 engines finding an Evo-gen Trojan.

![grafik](https://github.com/user-attachments/assets/0f78536c-b150-455f-a3f7-e11eec44c8eb)

False positive?

Please advise.

**Comment by chrisoro** [comment]
Well, the code is all open source (as you can see here). Some antivirus programs flag tools for various reasons - in our case, it's most likely because we grab your screen and control your mouse.

Feel free to join our Discord and see for yourself by asking our many users.
