### ISSUE TITLE
Filter Affixes not working 

### ISSUE THREAD

**Issue by tikalein** [aeon0/d4lf#359]
`- Amulet:
    affixPool:
    - count:
      - {name: to_conjuration_mastery}
    itemType: [amulet]`
![image](https://github.com/user-attachments/assets/3ef9d818-6fcb-408f-984b-db7e6506693a)
`- Staff:
    affixPool:
    - count:
      - {name: lucky_hit_up_to_a_chance_to_restore_primary_resource}
    itemType: [staff]   `
![image](https://github.com/user-attachments/assets/e7ac44d0-b777-42c4-a6da-805c9655ae12)

Both items are redflagged 

![image](https://github.com/user-attachments/assets/64a75244-c628-4d09-bad0-06c6a496ce19)

`2024-08-14 | 15:51:54.511 | ThreadPoolExecutor-0_0 | WARNING | src.item.descr.find_affixes:125 | Affix does not exist: cleaned_str='critical strike damage skills deal up to increased damage based on your available primary resource when cast, receiving the maximum benefit while you have full primary resource.' ||| combined_lines='+96.0% critical strike damage [80.0 - 100.0)% skills deal up to 16%[x] [10 - 40]% increased damage based on your available primary resource when cast, receiving the maximum benefit while you have full primary resource. requires level 80 sorcerer sell value: 103,174 durahilite 100100,'`

There might be more bugs regarding affixes
Version 5.7.3

**Comment by tikalein** [comment]
![image](https://github.com/user-attachments/assets/3ebd85b4-15e2-4c7d-a954-a169f8a82ec5)
![image](https://github.com/user-attachments/assets/2a738e46-a8f3-44b7-b1b7-95d11bec5fcb)

**Comment by chrisoro** [comment]
Thank you. I won’t be at my PC until Sunday, but please try out version 5.7.4 and see if it helps. A user on Discord confirmed that it works for 1080p with small and medium settings.

**Comment by tikalein** [comment]
![image](https://github.com/user-attachments/assets/cc66151b-f30d-4ff4-86a6-696011e1aa5e)
`- ChestArmor:
    affixPool:
    - count:
      - {name: intelligence}
      - {name: maximum_life}
      minGreaterAffixCount: 0
    itemType: [chest armor]`

Still not working in 5.7.5 

I like to help is there a debug mode ?

**Comment by chrisoro** [comment]
The item is detected properly in 5.7.5.

**Comment by tikalein** [comment]
![image](https://github.com/user-attachments/assets/910b0039-f3e4-48e1-9eb6-05caf31aa819)
Correctly filtered in 5.6.4
![image](https://github.com/user-attachments/assets/a56fc3d3-f8d0-4133-8f78-5423b8299b2d)
not filtered in 5.7.5

Is there a way to dump the ocr results just to see if its a ocr problem or the bug is elsewhere ?

**Comment by chrisoro** [comment]
We can run our detection on a screenshot, that is what I have done to verify it working in 5.7.5

**Comment by chrisoro** [comment]
multi lines should be fixed with 5.7.6

**Comment by tikalein** [comment]
![image](https://github.com/user-attachments/assets/eca5bce1-57a4-437f-9bec-fa5ca320ab18)
![image](https://github.com/user-attachments/assets/38496cc1-3cae-4d6e-9e3e-35de4ebe3cc1)
![image](https://github.com/user-attachments/assets/9a1de5e8-3ff0-4e6d-af54-24e59cca91e4)

still red bordered in 5.7.7 while correctly green in 5.6.4

**Comment by chrisoro** [comment]
I just ran it and the detection is 100%. So it can't be a detection issue. What is your filter?

**Comment by tikalein** [comment]
how can it get your screen ?

the filter is:

`- Staff:
    affixPool:
    - count:
      - {name: intelligence}
      - {name: critical_strike_damage}
      - {name: maximum_life}
      minCount: 2
      minGreaterAffixCount: 1
    itemType: [staff]`

but i the filter works in 5.6.4 so i would say the yaml.file is fine

**Comment by chrisoro** [comment]
> how can it get your screen ?
I ran our code from source as debug. No other easy way.

> the filter is:
> 
> `- Staff: affixPool: - count: - {name: intelligence} - {name: critical_strike_damage} - {name: maximum_life} minCount: 2 minGreaterAffixCount: 1 itemType: [staff]`
> 
> but i the filter works in 5.6.4 so i would say the yaml.file is fine

can you format it correctly or upload the file to pastebin? indentation is important.

**Comment by tikalein** [comment]
![image](https://github.com/user-attachments/assets/6544b605-f450-44a3-a8f5-d3faf1bf8826)
the code is created by the gui

**Comment by chrisoro** [comment]
It is detected and filtered correctly. No idea why it isn't working on your end :(

**Comment by tikalein** [comment]
That's why i asked how to debug it, i use Visual Studio but in C++/C#. I am doing my best to set it up for python

**Comment by chrisoro** [comment]
Can you send me a full screenshot where you are hovering over the item? Without d4lf running of course.
Btw hop into our discord, easier to chat ;)

**Comment by tikalein** [comment]
![image](https://github.com/user-attachments/assets/0fb0f1ce-727b-4a96-a496-7fb01af272ed)
i am in the discord :-)

**Comment by chrisoro** [comment]
As discussed, increasing resolution and/or quality solved the issue
