### ISSUE TITLE
Lucky Hit Execute Incorrect in Affixes.json

### ISSUE THREAD

**Issue by RadDude42** [aeon0/d4lf#62]
Line 79 needs to be updated to below as it currently  cannot read the affix

"lucky_hit_up_to_a_chance_to_execute_injured_nonelites": "lucky hit up to a chance to execute injured nonelites",

**Comment by aeon0** [comment]
Can you give me a screenshot of an item with that affix so I can check. The text is "cleaned". All numbers, :, -, %, [] will be removed.

"Lucky Hit: Up to [4.4 - 10.0]% Chance to Execute Injured Non-Elites"
will be
"lucky hit up to chance to execute injured nonelites"

**Comment by aeon0** [comment]
Should be fixed in v2.2.2. Thanks for the report.
