### ISSUE TITLE
Request - Filter Rule Name

### ISSUE THREAD

**Issue by LostPoE** [aeon0/d4lf#63]
When a rule matches. Is it possible to have it display the rule name that matches with the box that surrounds the loot? Thanks!

**Comment by aeon0** [comment]
I would claim it alread does:
![grafik](https://github.com/aeon0/d4lf/assets/15958535/e151bb3a-fcc4-4ee1-bd59-fabda933ea24)

the item matches the filter called "Helm" in the file general.yaml.

**Comment by aeon0** [comment]
added in 2.2.3
