### ISSUE TITLE
Support for controller

### ISSUE THREAD

**Issue by zhaoyuheng200** [aeon0/d4lf#68]
Hi aeon0, thank you for the great app.
Is it possible to add support for xbox controllers？
Or you can point me to the direction, I can look into it as well.

Thanks,
Neil

**Comment by NoNameTrademark** [comment]
Juste use a tools for remaping the controller inputs. Lot of tools for that. like "JoyToKey'. If you play with steam, there is a mapper built into it.

**Comment by zhaoyuheng200** [comment]
Sorry I don't quite follow how to use JoyToKey to achieve that.
For "xbox controllers support", I mean I'm a xbox controller user on PC,
The filter tool sometimes doesn't trigger the gray/red/green filter box when using a controller to navigate between items.
AFAIK the filter triggers if the item has been previous mouse overed and then "focused" by using controller.

**Comment by aeon0** [comment]
Dont you have completely different layout when using controller? The tool has hardcoded values for the grids in the inventory and stash (adjusted only by resolution). So I assume that is what you see. The tool thinks your items are alligned differently than they really are and thats why you see such inconsisten behaviour.

Adjust could be done. But hard for me to test :/

**Comment by zhaoyuheng200** [comment]
>Dont you have completely different layout when using controller? 

Thanks for replying!
Not completely , I see them as the same. Can you point me to the direction to adjust it please?

**Comment by aeon0** [comment]
So for now, the only way is to map somehow a controller button to the hotkeys, or to have a keyboard alongside. I don't think we will have native controller support anytime soon. Sorry. Closing for now.
