### ISSUE TITLE
Resistance

### ISSUE THREAD

**Issue by Teberon** [aeon0/d4lf#72]
It would be great to be able to use "any_resistance" without specifying which one

**Comment by shimo-sudo** [comment]
To do this without any changes to the codebase you could add all resistance affixes to your profile

**Comment by Teberon** [comment]
But doesn't all resistance exist and it would look for that value? Sorry, have used it so far only for two nm dungeons and not further tested

**Comment by aeon0** [comment]
Yeah, I think best is to just add then all resitance types to the affix pool as @shimo-sudo mentioned. I dont want to do any special thing here to be honest. Lets keep things simple that are simple :)
