### ISSUE TITLE
Imprinted Aspects should not be taken into account

### ISSUE THREAD

**Issue by Teberon** [aeon0/d4lf#89]
Legendaries with imprinted aspects should not be shown green for an aspect check, but only for affixes

**Comment by Teberon** [comment]
For example:

With level 60 I got an item with 2 / 4 affixes to get the armor. It will always try to keep the item because of the imprinted aspect but should drop it cause the affixes don't match that slot anymore

**Comment by aeon0** [comment]
Exactly. Since you imprinted the aspect, you probably want to keep that item. I dont want to risk marking it as junk. If you want to trash it because you found sth better, you should do that manually.
