### ISSUE TITLE
Filter Sigils and Dungeons

### ISSUE THREAD

**Issue by brunosw** [aeon0/d4lf#97]
It would be nice if we could also filter sigils based on dungeons and affixes.

**Comment by NoNameTrademark** [comment]
Cool little things to do for sigils. 

In green the favorite sigils:
-A list of dungeon names that you want to favor
-No negative affix which is displayed in the negative list previously filled in (See the sigils in red)

In red the negative sigils:
-A list of affixes to avoid having on sigils
-A list of dungeons not to choose
-In green takes into account that there must be none of the points above

In gray (Or yellow/orange to differentiate the gray which displays poor detection)
-Sigils with a dungeon name and an affix that does not match any of the two entries above


Afterwards, to push it even further, make a list like the items.
Exemple of a sigils.yaml:


# **Whitelist this is what we would like to have**
#   dungeonName, blackAffix, minLevel, tierList, dungeonType can be left blank
#
# **The blacklist is there to list what we really don't want**
#   dungeonName, blackAffix, minLevel, tierList, dungeonType can be left blank
#
# **tierList is just for overlay in bottom corner**
#   tierList must be any of:
#     A, B, C, D, E, F, etc (it's just overlay text anyway)
#  
#  **dungeonName must be one of the name in dungeons.json
#
# **dungeonType is just for overlay in bottom corner**
#   dungeonType must be any of:
#     XP, Glyphe, Gold, Unique, comps, etc (it's just overlay text anyway)
# 
# **blackAffix must be one of the affixes in sigils.json


Whitelist:
  - FilterDescription_Model_Good_1:
      dungeonName: [belfry_zakara,aldurwood,abandoned_mineworks]
      minLevel: 50
      tierList: A
	  dungeonType: [XP,Glyph]
	 
  - FilterDescription_Model_Good_2:
      dungeonName: buried_halls
      minLevel: 45
      tierList: B
	  dungeonType: XP
	  
BlackList:
# Marks all the belfry_zakara, aldurwood, abandoned_mineworks in red
  - FilterDescription_Model_Bad_1:
      dungeonName: [belfry_zakara,aldurwood,abandoned_mineworks]
	  blackAffix:
      minLevel:
      tierList: S
	  dungeonType: [XP,Glyph]

# All sigils up to 70
  - FilterDescription_Model_Bad_2:
      dungeonName:
	  blackAffix:
      minLevel: 70
      tierList: S
	  dungeonType: [XP,Glyph]

# All sigils under level 50
  - FilterDescription_Model_Bad_3:
      dungeonName:
	  blackAffix:
      minLevel: [50, under]
      tierList: S
	  dungeonType: Glyph
	  
# All sigils with the quick_killer afix 
  - FilterDescription_Model_Bad_4:
      dungeonName:
	  blackAffix: quick_killer
      minLevel:
      tierList: Whatyouwant
	  dungeonType: Whatyouwant

**Comment by NoNameTrademark** [comment]
> Do you have the configuration file? .yaml?

Not implemented yet

**Comment by aeon0** [comment]
Implemented on master now. But only with a blacklist filtering, no where near as detailed filtering as suggested from @NoNameTrademark
